# Workflow derived from https://github.com/r-lib/actions/tree/master/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  schedule:
    # monday to friday at 8:00
    - cron:  '0 8 * * 1,2,3,4,5'

name: rjd-stats

jobs:
  downloads-stats:
    runs-on: macos-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v1

      - name: Install package
        run: |
          R -e 'install.packages("rvest")'
          R -e 'install.packages("lubridate")'
          R -e 'install.packages("cranlogs")'

      - name: Download Statistiques
        run: Rscript cran_downloads_stats.R

      - name: Commit files
        run: |
          git config --local user.name actions-user
          git config --local user.email "actions@github.com"
          git add data/*
          git commit -am "GH ACTION Headlines $(date)"
          git push origin main

        env:
          REPO_KEY: ${{secrets.GITHUB_TOKEN}}
          username: github-actions

